config/routes.rb
Rails.application.routes.draw do
  resources :goals, only: [:create, :destroy] do
    post :done, action: :done
  end

  resources :daily_achievements, only: [:create, :index]

  scope module: :users do
    resources :profiles, only: [:edit, :update] do
      post :set_locale, action: :set_user_locale
      post :set_background, action: :set_background
    end
  end

  devise_for :users, controllers: {
    sessions:           "users/sessions",
    registrations:        "users/registrations",
    passwords: "users/passwords"
  }

  root to: "daily_achievements#index"
end

app/models/background.rb
class Background < ActiveRecord::Base
  belongs_to :user

  mount_uploader :background, BackgroundUploader

  validates :background, presence: true

  scope :active, -> { where(active: true) }
end

app/models/daily_achievement.rb
class DailyAchievement < ActiveRecord::Base
  belongs_to :user

  validates :text, uniqueness: true, presence: true
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  belongs_to :user

  validates :description, presence: true

  scope :undone, -> { where(done: false) }
  scope :done, -> { where(done: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :avatar, AvatarUploader

  validates :email, presence: true

  has_many :goals

  has_many :daily_achievements

  has_many :backgrounds

  def active_background_url
    background = backgrounds.active.first
    background.background_url if background
  end

  def name_or_email
    return full_name if full_name.present?

    email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication

  before_action :authenticate_user!
  before_action :set_locale

  protect_from_forgery with: :exception

  private

  def set_locale
    I18n.locale = current_user.locale if current_user
    I18n.locale ||= I18n.default_locale
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  private

  def devise_parameter_sanitizer
    if resource_class == User
      User::ParameterSanitizer.new(User, :user, params)
    else
      super
    end
  end
end

app/controllers/daily_achievements_controller.rb
class DailyAchievementsController < ApplicationController
  def index
    @daily_achievement_presenter = {
      daily_achievements: current_user.daily_achievements,
      form: {
        action: daily_achievements_url,
        csrf_param: request_forgery_protection_token,
        csrf_token: form_authenticity_token
      }
    }

    @goal_presenter = {
      undone_goals: current_user.goals.undone,
      done_goals: current_user.goals.done.last(5),
      form: {
        action: goals_url,
        csrf_param: request_forgery_protection_token,
        csrf_token: form_authenticity_token
      }
    }
  end

  def create
    @daily_achievement = current_user.daily_achievements.create(daily_achievement_params)

    if request.xhr?
      render json: current_user.daily_achievements
    else
      redirect_to daily_achievements_path
    end
  end

  private

  def daily_achievement_params
    params.require(:daily_achievement).permit(:id, :text)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def create
    @goal = current_user.goals.create(goal_params)

    if request.xhr?
      render json: current_user.goals.undone
    else
      redirect_to daily_achievements_url
    end
  end

  def done
    @goal = Goal.find(params[:goal_id])

    @goal.update_attributes(done: true)

    render json: {}
  end

  def destroy
    @goal = Goal.find(params[:id])

    @goal.destroy

    render json: {}
  end

  private

  def goal_params
    params.require(:goal).permit(:id, :description, :start_at, :end_at)
  end
end

app/controllers/users/passwords_controller.rb
module Users
  class PasswordsController < Devise::PasswordsController
    layout "on_board"
  end
end

app/controllers/users/profiles_controller.rb
module Users
  class ProfilesController < ApplicationController
    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])

      if @user.update_attributes(user_params)
        redirect_to edit_profile_url(@user)
      else
        render :edit
      end
    end

    def set_user_locale
      locale = params[:locale]

      current_user.locale = locale
      current_user.save
      redirect_to :back
    end

    def set_background
      background = current_user.backgrounds.create(background_params)

      current_user.backgrounds.active.each do |active_background|
        active_background.update_attributes(active: false) unless active_background == background
      end

      redirect_to edit_profile_url(current_user)
    end


    private

    def user_params
      params.require(:user).permit(
        :full_name, :email, :avatar
      )
    end

    def background_params
      params.require(:background).permit(
        :background
      )
    end
  end
end

app/controllers/users/registrations_controller.rb
module Users
  class RegistrationsController < Devise::RegistrationsController
    layout "on_board"
  end
end

app/controllers/users/sessions_controller.rb
module Users
  class SessionsController < Devise::SessionsController
    layout "on_board"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_achievements_helper.rb
module DailyAchievementsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/application/_navigation.html.slim
header class="main-header"

  nav class="navbar navbar-static-top"
    .container
      .navbar-header.col-xs-4
        = link_to root_url, class: "navbar-brand" do
          b
            = t("personal")
          = t("journal")

      .navbar-custom-menu
        ul class="nav navbar-nav"
          li class="user user-menu"
            = link_to edit_profile_path(current_user) do
              = image_tag current_user.avatar.url || "user3-128x128.jpg", class: "user-image"
              span
                = current_user.name_or_email
          li
            = link_to "eng", profile_set_locale_url(current_user, locale: "en"), method: :post
          li
            = link_to "рус", profile_set_locale_url(current_user, locale: "ru"), method: :post
          li
            = link_to t("logout"), destroy_user_session_url, method: :delete

app/views/daily_achievements/index.html.slim
.col-md-4.col-md-push-8
  = react_component("GoalBox",
      {presenter: @goal_presenter.to_json,
        goal_title: t("goal.title"),
        done_goal_title: t("done_goal.title"),
        goal_form: t("goal.form")},
      {prerender: true})
.col-md-8.col-md-pull-4
  = react_component("DailyAchievementBox",
    {presenter: @daily_achievement_presenter.to_json,
      daily_achievement_locale: t("daily_achievement")},
    {prerender: true})

app/views/layouts/application.html.slim
doctype html
html
  head
    title PersonalJournal. Your personal Journal

    meta name="description" content="Write your personal stories. Keep your inner-most feelings private."

    meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport"


    link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"

    link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css"

    = stylesheet_link_tag "application", media: "all"
    = csrf_meta_tags

  body class="hold-transition skin-green layout-top-nav"
    div class="wrapper"
      = render "navigation"

      div class="content-wrapper container-fluid" style="background-image: url(#{current_user.active_background_url}); background-size:100%;
    background-attachment: fixed;"
        section class="content"
          = yield

    script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.10.2/moment.min.js"
    = javascript_include_tag "application"

app/views/layouts/on_board.html.slim
doctype html
html class='no-js' lang='en'
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=edge"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    meta name="description" content=""
    meta name="author" content=""

    = csrf_meta_tags

    = stylesheet_link_tag "application"
    = javascript_include_tag "application"

    title PersonalJournal

  body class="hold-transition login-page"
    .login-box
      .login-box-body
        .login-logo
          b Personal
          | Journal
        = yield

app/views/users/profiles/edit.html.slim
section class="content"
  div class="box box-primary"
    .box-header
      h3 class="box-title"
        = t "profile.edit.title"

    .box-body
      .col-md-4
        = simple_form_for(Background.new, url: profile_set_background_url(current_user), html: { method: :post, class: "form-horizontal" }) do |f|
          label
            = t("background_image.background_image")
          .col-md-12
            = image_tag(current_user.active_background_url, width: 200, height: 200, class: "upload-preview2")
            = f.file_field :background, class: "image_to_upload2"

            = f.submit t("background_image.set_image"), class: "btn btn-info btn-flat"

      = simple_form_for(@user, url: profile_path(@user), html: { method: :put, class: "form-horizontal" }) do |f|

        .col-md-3.col-md-span-1
          label = t("profile.edit.avatar")
          .col-md-12
            = image_tag(@user.avatar_url, width: 200, height: 200, class: "upload-preview")
            = f.file_field :avatar, class: "image_to_upload"

        .col-md-4
          .form-group
            .col-md-4
              label
                = t("profile.edit.labels.email")
            .col-md-8
              .input-group
                span class="input-group-addon"
                  i class="fa fa-envelope"
                = f.input :email, label: false, input_html: { class: "form-control" }

          .form-group
            .col-md-4
              label
                = t("profile.edit.labels.full_name")

            .col-md-8
              = f.input :full_name, label: false, input_html: { class: "form-control" }

          = f.submit t("profile.edit.update_profile"), class: "btn btn-info btn-flat"